[APP]
api_url = http://localhost:8080/api
app_version = 2026.4.3
publish_arch = amd64
publish_origin = MyOrg
publish_label = MyLabel
allowed_codename = bionic,jammy

[LOGGING]
log_level = INFO
log_max_bytes = 1048576
log_backup_count = 5
